name: music
description: A local music player app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  audiotags: ^1.4.2
  file_picker: ^8.0.0
  path_provider: ^2.1.4
  permission_handler: ^12.0.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
